name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci 

    - name: Install ESLint dependencies (CI only)
      run: |
        npm install --save-dev eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin

    - name: Lint
      run: npm run lint

    - name: Run unit tests
      run: npm test -- --watchAll=false

    - name: Build
      run: npm run build
